### ISSUE TITLE
Usage with single component issue

### ISSUE THREAD

**Issue by oarashi** [salvoravida/react-adal#1]
Hi! Thanks for library! 
Can you please provide an example of usage with adal only one component (not the whole application).
I have only one component (on one url) where it is required an authorization with azure.
Thanks!
And thanks one more time for your library!

**Comment by salvoravida** [comment]
Hi!
Do you mean integration with react-router on only one Route?

**Comment by oarashi** [comment]
@salvoravida Yes (and I had to use hashRouter from React router v4). But I was thinking about wrapping with runWithAdal not the application itself, but only specific component. E.g. on component didMount manipulate with adal and then decide what to do - show component if user authorized/show component with error message/ redirect to login.
Thanks!

**Comment by argrithmag** [comment]
Was there a example of this made?  I actually have the "opposite" problem.  I'd like a landing page that doesn't have any auth on it (allows anonymous), but if they either go to any other part of the app, or click on a "login" button on that landing page, then it directs them to the login.

**Comment by salvoravida** [comment]
react router integration for partial web app AD support is a to do feature...

**Comment by salvoravida** [comment]
done!

**Comment by harshsrivastava50896** [comment]
can you show example for this login page

**Comment by harshsrivastava50896** [comment]
If I render the login page and in it I call "runwithadal" after authentication it does not load the next component

**Comment by salvoravida** [comment]
> If I render the login page and in it I call "runwithadal" after authentication it does not load the next component

see on readme.
