### ISSUE TITLE
How to specify the webApi endpoint

### ISSUE THREAD

**Issue by skypyxis** [salvoravida/react-adal#10]
On adalConfig.js how can we specify an endpoint different from 'api'? (e.g. 'http://localhost:5000/api/')

If I do this:
```
export const adalConfig = {
    tenant: '<tenant>',
    clientId: '<clientid>',
    endpoints: {
        'http://localhost:5000/api/': '<webapi_appid>',
    },
   cacheLocation: 'localStorage',
};
```

I get this error on adalApiFetch: 
Uncaught (in promise) {message: "resource is required", msg: "resource is required"}

**Comment by salvoravida** [comment]
?!?! i think you are a little bit confused:

endpoints are the GUID of azure Active Directory web app that host your api.

for example if you have 2 api web-endpoint

https://myapi1.azurewebsites.net has a GUID 'XXXXXXX......'
https://myapi2.azurewebsites.net has a GUID 'YYYYYYY......'

Here is adalConfig.js

```javascript

import { AuthenticationContext, adalFetch } from 'react-adal';

export const adalConfig = {
  tenant: 'AZURE ADAL TENTEN GUID',
  clientId: 'AZURE APP CLIENT ID',
  endpoints: {
    myapi1: 'XXXXXXXXXXXXXXX',
    myapi2: 'YYYYYYYYYYYYYYY',
  },
  cacheLocation: 'localStorage',
};

export const authContext = new AuthenticationContext(adalConfig);

export const adalApi1Fetch = (fetch, url, options) =>
  adalFetch(authContext, adalConfig.endpoints.myapi1, fetch, url, options);

export const adalApi2Fetch = (fetch, url, options) =>
  adalFetch(authContext, adalConfig.endpoints.myapi2, fetch, url, options);

```

**Comment by sealightPT** [comment]
Thank you!
I thought "endpoints" was a dictionary (key, value) of (baseUrl, webAppGuid) but it isn't.

Your example of 
`export const adalApi1Fetch = (fetch, url, options) =>
  adalFetch(authContext, adalConfig.endpoints.myapi1, fetch, url, options);`

made it very clear of how it is being used!
Thanks!
