### ISSUE TITLE
Token renewal operation failed due to timeout

### ISSUE THREAD

**Issue by Laksh05** [salvoravida/react-adal#100]
After one hour when token gets expired I call api to get data. Iframe silently try to refresh the token. Api failes to get data and in console error comes "Token renewal operation failed due to timeout".

![image](https://user-images.githubusercontent.com/15712455/71764756-f33c8280-2f11-11ea-9a8c-b4f34346feb8.png)

**Comment by Laksh05** [comment]
Sorry for raising issue. I got solution checked adal.js in nodemodules(@property {number} loadFrameTimeout The number of milliseconds of inactivity before a token renewal response from AAD should be considered timed out.). Added loadFrameTimeout to 30 sec. Working fine now. 

Thank you. Your library is great :)

**Comment by linchen2chris** [comment]
@Laksh05  may I know how you config loadFrameTimeout to 30 sec?
is 
``` js
const adalConfig = {
tenant: "xxx",
clientId: "xxx",
cacheLocation: "localStorage",
loadFrameTimeout: 30 * 1000
}
```
Thanks

**Comment by Laksh05** [comment]
@linchen2chris  Yes correct for 30 seconds you can write it as 30000.

**Comment by linchen-myob** [comment]
@Laksh05 after I set loadFrameTimeout, and after 30s it fails, I got error like "Load denied by X-Frame-Options: “DENY” from ", did you have the error as well?

**Comment by Laksh05** [comment]
@linchen-myob  Yes I also got. You have to mention X-frame-options="SAMEORIGIN" in web config.

**Comment by linchen-myob** [comment]
Hi @Laksh05 could you explain more, how config that? in my backend or my chrome?

**Comment by Laksh05** [comment]
Hi @linchen-myob  In backend where you have deployed application. You need to change custom header X-Frame-Options. Mention X-frame-options="SAMEORIGIN"
