### ISSUE TITLE
Dependencies - adal

### ISSUE THREAD

**Issue by vladavip88** [salvoravida/react-adal#11]
Hey, I really like your work, but your script depends on **adal**, so it would be nice to add **adal** as dependencies, not to include it directly. Also, it would be cool to add 'logOut' function.

**Comment by matthew-matvei** [comment]
> Also, it would be cool to add 'logOut' function.

I believe you can just use the underlying authentication context and do `authContext.logout()`, no?

**Comment by vladavip88** [comment]
Ah, yes, cool, works perfectly, thanks! ;)

**Comment by AFSDevGuy** [comment]
Love it! Agree with the dependency issue, though. Maybe I'll fork and send you a pull request...

Thanks!

**Comment by salvoravida** [comment]
Hi!
until 1.0.16 adal.js has a bug not yet merged so local patched adal.js was required.
https://github.com/AzureAD/azure-activedirectory-library-for-js/pull/674

Anyway currently Microsoft has a single lib for adal and adal-angular ...
so i think it's better to have local adal.js until MS decide to extract adal.js from adal-angular ...

I'm releasing a new version with adal updated to 1.0.17 and single Route Component login.
Stay in touch.

**Comment by salvoravida** [comment]
1.0.17 released updated on react-adal 0.4.17
