### ISSUE TITLE
Microsoft Is Retiring ADAL For MSAL

### ISSUE THREAD

**Issue by opticyclic** [salvoravida/react-adal#113]
This post says that Microsoft is retiring ADAL
https://techcommunity.microsoft.com/t5/azure-active-directory-identity/update-your-applications-to-use-microsoft-authentication-library/ba-p/1257363

Will this library continue to work with their new MSAL scheme or is that the job of a different project?

**Comment by salvoravida** [comment]
yes will be upgraded in react adal 2.0
