### ISSUE TITLE
Source code differences between npmjs.com and github.com

### ISSUE THREAD

**Issue by mackankowski** [salvoravida/react-adal#117]
Hi @salvoravida,

I can see that the codebase fetched from https://www.npmjs.com/package/react-adal (by `npm i`) is different than in this repository - as well, library versions are not the same. Can you update the Github repository, Release section, and version in the `package.json`? I'd like to put a new PR with code improvement but not it's a little bit messy (I have also build issues with the previous `0.5.0` version).

Thank you in advance,
Maciej

**Comment by salvoravida** [comment]
done
