### ISSUE TITLE
React-Dom dependency requires SharedArrayBuffer which will require cross-origin isolation

### ISSUE THREAD

**Issue by FizzBuzz791** [salvoravida/react-adal#119]
See this issue for more information; https://github.com/facebook/react/issues/20829

The tl;dr is that people could start running into problems quite soon (May 2021!). This has been fixed in React 17+ and upgrading the react-dom dependency of this package, should also resolve this issue.

**Comment by salvoravida** [comment]
react-dom is not needed for react-adal. it's just a dev dep

**Comment by FizzBuzz791** [comment]
@salvoravida - I think this call stack indicates otherwise...

![image](https://user-images.githubusercontent.com/2747764/115327897-57945b80-a1c2-11eb-9a7a-e17a7d352bff.png)
