### ISSUE TITLE
How best to handle errors with adalFetch

### ISSUE THREAD

**Issue by matthew-matvei** [salvoravida/react-adal#12]
Trying to use `adalFetch`, I see that the underlying `adalGetToken` it calls will reject when it fails to retrieve a token for the pointed-to resource?

Is it simply to `authContext.login()` on the next line? Trying to do this, I seem to get a no-op (no redirection, prompt etc.) when calling that login method. It would indicate to me that the `authContext` thinks I'm logged in (cached user?), despite the `authContext.acquireToken` not getting a token. I consistently receive a `login_required` error from adal on Chrome (Firefox seems to work, other browsers break with other problems).

**Comment by salvoravida** [comment]
adalFetch.catch(error=> if error.msg==="login required" ....)
