### ISSUE TITLE
Articles

### ISSUE THREAD

**Issue by Odonno** [salvoravida/react-adal#13]
I wrote a new article on medium about my recent experience on Azure AD + React + ASP.NET Core.
I hope you will enjoy it.

Here is the link: https://medium.com/@dbottiau/a-memo-on-how-to-implement-azure-ad-authentication-using-react-and-net-core-2-0-3fe9bfdf9f36

And thanks for hte lib by the way. ;)

**Comment by salvoravida** [comment]
hi! thanks!
maybe you want to update your article with new withAdalLogin HOC.

**Comment by Odonno** [comment]
@salvoravida What does it do?

**Comment by salvoravida** [comment]
withAdalLogin HOC
- support login only on a Page/Route Component
- change DO_NOT_LOGIN to true on index.js to stop login on index.js

adalConfig.js
```
export const withAdalLoginApi = withAdalLogin(authContext, adalConfig.endpoints.api);
```

Example :
```
import MyPage from './myPageComponent';
import Loading from './Loading';
import ErrorPage from './ErrorPage';

const MyProtectedPage = 
withAdalLoginApi(MyPage, () => <Loading />, (error) => <ErrorPage error={error}/>);

<Route 
   path="/onlyLoggedUsers"
   render={ ()=> <MyProtectedPage /> } 
/>
```

**Comment by imsam67** [comment]
I'm trying to understand this and use it in my ASP.NET Core 2.1 app with ReactJs frontend.

I'm using React Router and my `App.jsx` looks like this:
```
class App extends Component {

   constructor(props) {
      super(props);
   }
   render() {
       return(
            <div>
                <Switch>
                       <Route exact path="/" component={Home} />
                       <Route exact path="/accounts" component={Accounts} />
                </Switch>
           </div>
       );
   }
}
```
My whole app requires authentication. How would I use the `withAdalLoginApi()`? I'm confused about where to use it. Am I doing what you show in every protected component or in the App.jsx?

**Comment by imsam67** [comment]
Sorry about questions on what you may find rudimentary but I'm trying to learn and understand this as I implement it.

Also, after I login through Azure AD B2C page and get redirected to my app, this is what I'm seeing:
![capture](https://user-images.githubusercontent.com/15844030/40094653-e6c98108-588d-11e8-92fc-e1f386e5aa45.PNG)

I'd like to see http://localhost:49065 or just https://myapp.com in the browser on production site. Seeing the access token there would be confusing to users. Should I not redirect to my home page/component after obtaining the token from Azure AD?
