### ISSUE TITLE
The options on adalFetch should be optional to match underlying fetch API

### ISSUE THREAD

**Issue by ydogandjiev** [salvoravida/react-adal#15]
When I converted my existing fetch calls to adalFetch most of them didn't work because I wasn't specifying any options:
![image](https://user-images.githubusercontent.com/3357245/38793718-355c972c-4107-11e8-8998-c67b627caeaf.png)

Fixing this would be pretty easy:
```
const o = options || {};
```

**Comment by salvoravida** [comment]
done thanks
