### ISSUE TITLE
Redirect loop if tenant is left to 'common'

### ISSUE THREAD

**Issue by rjbez17** [salvoravida/react-adal#20]
While using the library we can easily get it working if you provide the tenant ID or our active directory. However, we are trying to open this up to other organizations and removing the tenant parameter (leaving it as 'common') causes login redirect loops. There doesn't seem to be any errors in the sessionStorage indicating there was a login failure.

This works:

    const adal_config = {
        tenant:"my tenant id",
        clientId: "my client id"
    }

However this provides the loop:

    const adal_config = {
        tenant:"common",
        clientId: "my client id"
    }

Am I missing something?

**Comment by salvoravida** [comment]
react-adal just call authContext.login() that is from official adal.js

so try to call it without react-adal active, (index.js) and see how many redirect you have.

may be tenant is a mandatory field, cannot be "common"

see more on adal.js here https://github.com/AzureAD/azure-activedirectory-library-for-js
