### ISSUE TITLE
Is authentication done by the frontend?

### ISSUE THREAD

**Issue by atsepkov** [salvoravida/react-adal#21]
Thanks for the library, it's much more convenient for ADFS integration than SAML libraries I've tried. I'm concerned about security, however.

Added a couple `console.log` statements around `runWithAdal` logic and noticed that it fires in the frontend. So is it the frontend that verifies user authentication? Wouldn't that be susceptible to user tampering?

**Comment by salvoravida** [comment]
So is it the frontend that verifies user authentication? 

what do you mean?

Are you sure you know how JWT Token works?

https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-authentication-scenarios#single-page-application-spa
