### ISSUE TITLE
Unexpected token: name (React)

### ISSUE THREAD

**Issue by tarim** [salvoravida/react-adal#22]
Hi There,

I just updated latest react-adal. After update, when I run deploy, I got error message. Here are details

 `SyntaxError: Unexpected token: name (React) [./~/react-adal/lib/react-adal.js:10,0]`

any suggestion please?

thanks,

**Comment by salvoravida** [comment]
Which browser? Do you have React import in Your Project?

**Comment by tarim** [comment]
All browsers are same. It happened when I upgraded it to the latest version.

**Comment by salvoravida** [comment]
can you share your code?

**Comment by salvoravida** [comment]
closed. feel free to re-open if needed
