### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by levalencia** [salvoravida/react-adal#24]
Hello

1. Whats the difference between the 2 implementations, its not easy to understand.
2. Isnt the tenantid and clientid usually different? being client id the app registration id and tenant id the active directory id?

Thanks

**Comment by salvoravida** [comment]
please refer to official Azure Active directory page.

react-adal is just a wrapper for use it with react apps

**Comment by levalencia** [comment]
I google ADAL HOC and found nothing, in the readme I believe it should be clearer about the difference in the 2 implementations, BTW I already used it and it works perfect, but I just want to know what HOC means

**Comment by salvoravida** [comment]
https://reactjs.org/docs/higher-order-components.html
