### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by levalencia** [salvoravida/react-adal#26]
Hello

I see you posted a comment here:
https://github.com/AzureAD/azure-activedirectory-library-for-js/issues/481

I do  have a question though,  I have a webapp which is 100% UI only, no business logic, and I used your component to login and it works 100% fine.

However in my webapp at some point I will need to call a REST API, the REST API will be hosted in a different url in Azure, so I created another App Registration in Azure.

Can I use your component to authenticate the REST requests also?

If so, can you please guide me in the right direction? Can this be integrated with axios as the other user did in the previous post?

**Comment by salvoravida** [comment]
adalConfig.js

```javascript

import { AuthenticationContext, adalFetch, withAdalLogin } from 'react-adal';

export const adalConfig = {
  tenant: '14d71d65-f596-4eae-be30-27f079bf8d4b',
  clientId: '14d71d65-f596-4eae-be30-27f079bf8d4b',
  endpoints: {
    apiServer1: '14d71d65-f596-4eae-be30-27f079bf8d4b',  
    apiServer2: '2fhgfdshfsdhdfshsdfh-fdhsfd-27f079bxxx',  
  },
  cacheLocation: 'localStorage',
};

export const authContext = new AuthenticationContext(adalConfig);

export const adalApiServer1Fetch = (fetch, url, options) =>
  adalFetch(authContext, adalConfig.endpoints.apiServer1, fetch, url, options);

export const adalApiServer2Fetch = (fetch, url, options) =>
  adalFetch(authContext, adalConfig.endpoints.apiServer2, fetch, url, options);
```
Remeber to grant permission for clientId to apiServer1 and apiServer2 apps on Azure Cloud!

that's all!
