### ISSUE TITLE
adal api request sample

### ISSUE THREAD

**Issue by levalencia** [salvoravida/react-adal#27]
It worked perfect for my reactjs authentication, however I also have external custom apis that I need to call from within react, I guess the endpoints array is to list the app registration is from azure portal. Thats easy, done.

However, can you post an example of how to call a custom api?

**Comment by salvoravida** [comment]
i do not understand,
do you mean you have some other apis hosted not on active directory server?

if so you can you standard fetch or axios you do not need adal wrap!

**Comment by GroFin** [comment]
Hi @salvoravida  I too have the same question.

So my app is authorised within Azure AD however I wish to access the Microsoft Graph API's as well as the PowerBI API's.

Would I need to create 2 separate functions to call them such as this:


```
export const adalConfig = {
  tenant: 'tenent.onmicrosoft.com',
  clientId: 'ffffffff-fffff-ffff-ffff-fffffffffffffffff',
  endpoints: {
    graphApiUri: "https://graph.microsoft.com",
    api: 'ffffffff-fffff-ffff-ffff-fffffffffffffffff',
    powerbi: 'https://analysis.windows.net/powerbi/api',
    'https://graph.microsoft.com': 'https://graph.microsoft.com'
  },
  cacheLocation: 'localStorage'
};

export const graphApiFetch = (fetch, url, options) =>
  adalFetch(authContext, adalConfig.endpoints.graphApiUri, fetch, url, options);

  export const powerbiApiFetch = (fetch, url, options) =>
  adalFetch(authContext, adalConfig.endpoints.powerbi, fetch, url, options);

```

**Comment by TallOrderDev** [comment]
@GroFin most library maintainers do not watch closed tickets. If this is an issue you might want to open a new ticket and then link to this one. I know if I see a comment on an issue with a closed icon next to it, I just dismiss the notification.

**Comment by salvoravida** [comment]
> Hi @salvoravida I too have the same question.
> 
> So my app is authorised within Azure AD however I wish to access the Microsoft Graph API's as well as the PowerBI API's.
> 
> Would I need to create 2 separate functions to call them such as this:
> 
> ```
> export const adalConfig = {
>   tenant: 'tenent.onmicrosoft.com',
>   clientId: 'ffffffff-fffff-ffff-ffff-fffffffffffffffff',
>   endpoints: {
>     graphApiUri: "https://graph.microsoft.com",
>     api: 'ffffffff-fffff-ffff-ffff-fffffffffffffffff',
>     powerbi: 'https://analysis.windows.net/powerbi/api',
>     'https://graph.microsoft.com': 'https://graph.microsoft.com'
>   },
>   cacheLocation: 'localStorage'
> };
> 
> export const graphApiFetch = (fetch, url, options) =>
>   adalFetch(authContext, adalConfig.endpoints.graphApiUri, fetch, url, options);
> 
>   export const powerbiApiFetch = (fetch, url, options) =>
>   adalFetch(authContext, adalConfig.endpoints.powerbi, fetch, url, options);
> ```

yes you have to export one fetch wrapper for every endpoint
