### ISSUE TITLE
Page within Iframe

### ISSUE THREAD

**Issue by dnddbo** [salvoravida/react-adal#28]
I got this to work in a standalone react app but what if the react page is hosted in an iframe on a different site?
Can this work using the same iframe approach?

Thanks!

**Comment by salvoravida** [comment]
no! because adal login redirect and #hash authentication may corrupt the main window document/app.

**Comment by dnddbo** [comment]
Thank you for the answer! What about using the popUp: true setting then? Can you suggest any other approach? The react app has to be loaded inside an iframe cannot change that.

**Comment by salvoravida** [comment]
i think that you cannot use it on an iframe, anyway you should ask on offical adal.js page
https://github.com/AzureAD/azure-activedirectory-library-for-js
