### ISSUE TITLE
Unable to login: response_type 'token' is not enabled for the application

### ISSUE THREAD

**Issue by jfbloom22** [salvoravida/react-adal#29]
I have tried setting up my Azure app as a Web/API as well as Native, but I am getting: `response_type 'token' is not enabled for the application`
 any suggestions?

**Comment by salvoravida** [comment]
you should ask on official adal.js home
https://github.com/AzureAD/azure-activedirectory-library-for-js

react-adal it's just a wrapper for ReactJs.

**Comment by jfbloom22** [comment]
thx, figured it out.  Needed to setup:  After registration is completed, open Manifest file in Azure AD Portal, and set "oauth2AllowImplicitFlow:true". Got the plugin working.  Thanks for a great plugin!

**Comment by salvoravida** [comment]
you are welcome!

**Comment by adravi** [comment]
I was having the same problem. Thank you all.
