### ISSUE TITLE
Question: using adalApiFetch with an api?

### ISSUE THREAD

**Issue by missgrizzly** [salvoravida/react-adal#3]
I was wondering if you could elaborate on this part of the readme?

> use adalApiFetch with your favorite "fetch" in your api call.

Like with a sample?  Specifically with an api behind it would be amazingly helpful

**Comment by saostad** [comment]
+1

**Comment by uros-r** [comment]
+1

**Comment by andrralv** [comment]
` export function adalFetch(authContext, resourceGuiId, fetch, url, options) { `

The adalFetch function takes a fetch object, you can choose to use any npm package like Node-fetch or Axios and pass it on.

**Comment by salvoravida** [comment]
without ADAL you will fetch normally:
``` 
import fetch from 'isomorphic-fetch';
const myApiCall = () => fetch("www.domain.com/api/myapi", options)
```

if your domain is under ADAL then ..

``` 
import fetch from 'isomorphic-fetch';
import { adalApiFetch } from './adalConfig';
const myApiCall = () => adalApiFetch(fetch,"www.domain.com/api/myapi", options)
```
