### ISSUE TITLE
API GUID Endpoint

### ISSUE THREAD

**Issue by TallOrderDev** [salvoravida/react-adal#31]
First, great work on this, super simple and straight forward! Thanks!

Dumb question, first time really using Azure, so I'm still learning it's ins and outs. 

Is an API's endpoint GUID the same as it's TenantId, once it's been setup in AD as a registered app? 

Thanks in advance!

**Comment by salvoravida** [comment]
no. the api endpoint guid is the guid of azzure app that host the api app service.

anyway you could get more support on official adal.js page
https://github.com/AzureAD/azure-activedirectory-library-for-js

react-adal is only a React wrapper for the official lib adal.js
