### ISSUE TITLE
adal api request sample to multiple end points.

### ISSUE THREAD

**Issue by GroFin** [salvoravida/react-adal#32]
Hi @salvoravida 

So my app is authorised within Azure AD however I wish to access the Microsoft Graph API's as well as the PowerBI API's.

Would I need to create 2 separate functions to call them such as this:

```
export const adalConfig = {
  tenant: 'tenent.onmicrosoft.com',
  clientId: 'ffffffff-fffff-ffff-ffff-fffffffffffffffff',
  endpoints: {
    graphApiUri: "https://graph.microsoft.com",
    api: 'ffffffff-fffff-ffff-ffff-fffffffffffffffff',
    powerbi: 'https://analysis.windows.net/powerbi/api',
    'https://graph.microsoft.com': 'https://graph.microsoft.com'
  },
  cacheLocation: 'localStorage'
};


export const graphApiFetch = (fetch, url, options) =>
  adalFetch(authContext, adalConfig.endpoints.graphApiUri, fetch, url, options);

export const powerbiApiFetch = (fetch, url, options) =>
  adalFetch(authContext, adalConfig.endpoints.powerbi, fetch, url, options);
```

As with PowerBi, my main task is just to get the bearer token, is there a way to just get the adal token?

Thanks

**Comment by salvoravida** [comment]
right. the token is different for any endpoint. so you have to use a wrapper for each api endpoint.

**Comment by KoushikGoramane** [comment]
Hello @GroFin , I followed your approach but I am not getting user details from graph call.

My code
const adalConfig = {
    tenant: '',
    clientId: '',
    redirectUri: '',
    endpoints: {
        graphApiUri: "https://graph.microsoft.com",
        api: ''
    },
    cacheLocation: 'localStorage',
    postLogoutRedirectUri:''
};

export const authContext = new AuthenticationContext(adalConfig);

export const adalApiFetch = (fetch, url, options) =>
  adalFetch(authContext, adalConfig.endpoints.api, fetch, url, options);

export const graphApiFetch = (fetch, url, options) =>
  adalFetch(authContext, adalConfig.endpoints.graphApiUri, fetch, url, options);

  export const withAdalLoginApi = withAdalLogin(authContext, adalConfig.endpoints.api);
