### ISSUE TITLE
Access to roles/groups

### ISSUE THREAD

**Issue by levalencia** [salvoravida/react-adal#34]
How can I access roles or groups information ? Lets suppose I modified the manifest correctly to have groups or roles assigned to each user.

How can I access that information from react app to render different menu?

**Comment by MLWDev** [comment]
This would be useful. Is there an access token returned that can be used to call other endpoints?

**Comment by Alfetta159** [comment]
I would think that you would have to access the Graph API separately.

**Comment by levalencia** [comment]
according to this: 
https://stackoverflow.com/questions/40554525/role-group-based-authorization-using-adal-js-and-asp-net-web-api

we only need to edit the manifest to add the roles, the questions is how to get that information in the client app?

**Comment by DaveVoyles** [comment]
I'm looking for the exact same thing

**Comment by markau** [comment]
The roles should be returned in the access token. Does this work by any chance?

`authContext.getCachedUser().roles;`

**Comment by levalencia** [comment]
has anyone tested this? this is really important

**Comment by salvoravida** [comment]
hi, this is elated to adal.js you could access to authContext documented on offical adal.js page.
not related to this react wrapper.

**Comment by AWR14** [comment]
@salvoravida i've tried `authContext.getCachedUser().roles;` and its doesn't return anything.
any examples on getting roles and groups?

**Comment by Stacks-88** [comment]
Anyone learn how to retrieve roles?  Is is an Azure permissions issue?
