### ISSUE TITLE
Expecting window.local === window.parent limits use of this package

### ISSUE THREAD

**Issue by dggsax** [salvoravida/react-adal#35]
Thanks for the wrapper! One issue I've found is the extremely limiting requirement in which you've required under `runWithAdal()` that `window === window.parent`. For my use case I am trying to develop a VSTS Extension that lives within a website, so of course my code never passes this clause. Perhaps it might be helpful to expand the package so that users could either specify a regex for the root/context they expect to be working out of, or an alert if they don't pass the `window === window.parent` clause? Let me know what you think!

**Comment by salvoravida** [comment]
adal.js use iframes for silent login so if we do not put that condition, you will run React App on iframe too....

**Comment by iotarchitect** [comment]
@salvoravida having this same issue. Trying to embed a web page with react-adal inside another web page using an iframe. Can you suggest a work around?

**Comment by mattcasey** [comment]
I'm trying to use this inside a Teams Tab which uses iframes. I'll admit the authentication flow for Teams is confusing to say the least, but I thought that was a primary use case for this library.
