### ISSUE TITLE
Logout/Signout example

### ISSUE THREAD

**Issue by jeffaknine** [salvoravida/react-adal#36]
Hi, first of all thanks for the library, it's working great. I was wondering if anyone could provide an example on how to perform a sign out ?
Thanks

**Comment by salvoravida** [comment]
authContext.logOut()

**Comment by mudasar** [comment]
it is not working properly just redirects back to the application with logged in state. even clearing the application local storage doesn't logout completely? any help?

**Comment by psazop** [comment]
> it is not working properly just redirects back to the application with logged in state. even clearing the application local storage doesn't logout completely? any help?

I have exactly the same problem, could you solve it?

**Comment by gschauhan** [comment]
> it is not working properly just redirects back to the application with logged in state. even clearing the application local storage doesn't logout completely? any help?

Same issue. Any updates?
