### ISSUE TITLE
 ID_TOKEN response_type throws invalid request

### ISSUE THREAD

**Issue by theGlenn** [salvoravida/react-adal#37]
Version **0.4.18** uses only `id_token` for `response_type` and it redirect to `invalid_request` error page.
Using `response_type=id_token` works.

![Imgur](https://i.imgur.com/KLBp3M2.png)

**Comment by salvoravida** [comment]
Could you explain the issue better?

**Comment by salvoravida** [comment]
@theGlenn closed. just re-open if needed.
