### ISSUE TITLE
Single Component not rendering when using withAdalLoginApi

### ISSUE THREAD

**Issue by BjornVanWettere** [salvoravida/react-adal#38]
Hi

I've successfully used react-adal for my whole application before. However, this time around I only want the security context around 1 certain object (an action bar, the actions which are allowed are based on the user's security context). This is my code shortened:
```
import ActionBar from './ActionBar.jsx';
class Page extends React.Component  {
constructor(props) {
        super(props);
}

render() {      
        const actionBarWithAdal = withAdalLoginApi(ActionBar, () => <div>Loading</div>,(error) => <div>Error</div>);
return <div>{actionBarWithAdal}</div>
    }
}
```

```
class ActionBar extends React.Component {
    constructor(props) {
        super(props);

    componentDidMount() {
        console.log("Mounted");

        this.api.getActions(this.actionsCallback,this.apiErrorCallback);
    }
...
render(){
          console.log("Rendering");
          return <div>{this.state.apiActions}</div>;
      }
}
```

However, the code is never hitting the mount-method of this ActionBar. What am I doing wrong in my 'page'-component?

**Comment by salvoravida** [comment]
render() {      
        const actionBarWithAdal = withAdalLoginApi(ActionBar, () => <div>Loading</div>,(error) => <div>Error</div>);
return <div>{actionBarWithAdal}</div>
    }

What?!! ?!?!

const ActionBarWithAdal = withAdalLoginApi(ActionBar, () => <div>Loading</div>,(error) => 

and out of class!!!!

**Comment by BjornVanWettere** [comment]
I have absolutely no idea what you are trying to tell me. Can you clarify with a real example? Or indicate where I am doing something wrong. 

Maybe it's something I am trying, that is simply not supported. Because I don't have a real Route. It's just a component which I want to wrap in security.

**Comment by ethubert** [comment]
I also have the same problem, cannot render components once I try to remove the global SSO. The author's answer doesn't make any sense, I'll try to find a way and post the solution here.
