### ISSUE TITLE
Support MFA

### ISSUE THREAD

**Issue by ankitbko** [salvoravida/react-adal#39]
`withAdalLoginApi` flow fails when account is configured for MFA. Following error message is thrown - 
**AADSTS50079: The user is required to use multi-factor authentication.**

Based on [this](https://stackoverflow.com/a/46007643), to perform MFA, either ` acquireTokenPopup()` or `acquireTokenRedirect()` must be called as `acquireToken()` is not an interactive flow.

**Comment by salvoravida** [comment]
@ankitbko could you please confirm that this pr solved MFA?
