### ISSUE TITLE
Sorry, but we’re having trouble signing you in. We received a bad request.

### ISSUE THREAD

**Issue by saostad** [salvoravida/react-adal#4]
After I input user (hotmail account) information I got this error: 

> AADSTS50020: We are unable to issue tokens from this api version for a Microsoft account. Please contact the application vendor as they need to use version 2.0 of the protocol to support this.

here is my config file: 
```
import { AuthenticationContext, adalGetToken, adalFetch } from 'react-adal';

export const adalConfig = {
  tenant: 'common',
  clientId: '25fd0c46-6a83-550c-9a3e-c8214bfe0000',
  endpoints: {
    api: '25fd0c46-6a83-550c-9a3e-c8214bfe0000',
  },
  cacheLocation: 'localStorage',
};

export const authContext = new AuthenticationContext(adalConfig);

export const adalApiFetch = (fetch, url, options) =>
  adalFetch(authContext, adalConfig.endpoints.api, fetch, url, options);
```

**Comment by saostad** [comment]
I follow this instruction to create a tenant and now I can login: 

https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-howto-tenant#use-an-msa-azure-subscription

but I still don't know what is endpoint object? 
in App registeration section I have 7 endpoint. what should I do next? 
can you please provide an instruction of how to get diffrent part of config file?
and after that how to use it? how can I get current logged in user info and ...

**Comment by salvoravida** [comment]
endpoint.api is the GUID of your azure web api app that is under Active directory
