### ISSUE TITLE
Regarding: Redirecting to null page after running it in IIS 8.0

### ISSUE THREAD

**Issue by surendrakoritala** [salvoravida/react-adal#41]
Hi, 

I greatly appreciate for react-adal package. I added package in my react project and started using package to authenticate users with in the organization.  [url]/signin-oidc (url was localhost in dev environment and different for server) worked totally fine in localhost. but when the code was pushed to server that has IIS 8.0. It started giving me error message 'page does not exist'. Then i removed the signin-oidc as redirect URI. It started diverting to null page. and gave errors saying page does not exist. i removed the null at the end and it goes to my home page. I really want this to work in prod environment and don't want to ask users to remove null at the end of url. what should i do to get rid of null page routing. also why signin-oidc not working on IIS 8.0. It totally works fine on my local host.

**Comment by salvoravida** [comment]
are you sure you have correctly configurated iis for SPA application?
routing is client side so for every url IIS should return index.html

try search on google for it.
regards

**Comment by surendrakoritala** [comment]
Hi, Yes it is correctly configured, we are using following web.config:
<configuration>
    <system.webServer>

        

        <handlers>
            <add name="iisnode" path="server.js" verb="*" modules="iisnode" />
        </handlers>

        <rewrite>
            <rules>
                <rule name="sendToNode">
                    <match url="/*" />
                    <action type="Rewrite" url="server.js" />
                </rule>
            </rules>
        </rewrite>

    </system.webServer>
</configuration>

not sure, where it is going wrong. localhost:xxxx/signin-oidc works but with hostname/appname/signin-oidc just sends back hostname/appname/signin-oidc/#id_token=xxxxxxxx

Do you have any examples of re-routing. i am not sure how it works on localhost but not working on clientside server.
