### ISSUE TITLE
Stay signed in option not showing

### ISSUE THREAD

**Issue by rafaelgrilli92** [salvoravida/react-adal#42]
I had a nodejs server serving the client side (React) only to deal with the authentication, but then I took the nodejs out and I started to use this library on the client side instead. The thing is... the "stay signed in" option isn't showing anymore. I set it up on the azure portal to allow it, but it's still not working.

Any recommendations?

**That's what I want:**
![image](https://user-images.githubusercontent.com/21044452/48167691-9d397280-e340-11e8-879a-da08158628cb.png)

**Comment by salvoravida** [comment]
@rafaelgrilli92 https://github.com/AzureAD/azure-activedirectory-library-for-js/issues/272
