### ISSUE TITLE
Cannot recover from an old sid

### ISSUE THREAD

**Issue by lidermanrony** [salvoravida/react-adal#46]
react-adal cannot recover from Errors re-obtaining sign-in tokens after leaving browser window open a few days. 

This will only apply to application that enable sid in their AAD manifest (which is pretty rare).

Example error: Error AADSTS16002: Application requested a user session which does not exist. Trace ID: 057b129f-0717-489f-99fb-05ec121a3800 Correlation ID: cabaed52-02df-4e61-939f-4ba9151cc75e Timestamp: 2018-10-22 16:24:19Z clientRequestId: KustoWebV2;eb742095-98ac-49d4-80b9-08a692d46b29 

This should be fixed the same way MFA was fixed - call acquireTokenRedirect for these cases.

**Comment by salvoravida** [comment]
@lidermanrony feel free to re-open this issue if not works.
