### ISSUE TITLE
Why are we restricting when to allow redirects?

### ISSUE THREAD

**Issue by kouroshp** [salvoravida/react-adal#48]
I ran into an issue where the login flow needed to redirect to allow our app to access another API, this library prevented this redirect from happening and just errored out. Why not always allow the redirect to happen if the token is not successfully acquired? Is there any reason we check for specific status codes?
<img width="1543" alt="redacted" src="https://user-images.githubusercontent.com/4584978/50283396-b2301800-044d-11e9-9573-0f3968d52f71.png">

**Comment by salvoravida** [comment]
@kouroshp can you share error code ?
