### ISSUE TITLE
react-adal + axios

### ISSUE THREAD

**Issue by mrcnw** [salvoravida/react-adal#51]
How to combine adalFetch with axios?

**Comment by Jonwheeler** [comment]
Its in the readme:

```javascript
export const adalApiFetch = (fetch, url, options) =>
  adalFetch(authContext, adalConfig.endpoints.api, fetch, url, options);
```

The variable fetch passed here could be any lib you want.

```javascript
import axios from 'axios';
import { adalApiFetch } from 'adalConfig';

const myApiCall = () => adalApiFetch(axios.get, 'www.yourdomain.com/api/endpoint', options)
```

There are a number of other examples in the issue tracker if you search [axios](https://github.com/salvoravida/react-adal/issues?utf8=%E2%9C%93&q=axios)

**Comment by salvoravida** [comment]
@mrcnw  => @Jonwheeler thank you.
