### ISSUE TITLE
Question: multiple APIs with multiple client IDs

### ISSUE THREAD

**Issue by luminescent** [salvoravida/react-adal#52]
Hello 

My application needs two completely different tokens, for accessing different APIs, and each of them require a different client ID (I cannot change the permissions such that the client ID is the same). 

How could I configure for this situation? 

From what I have seen, the `ApplicationContext` is a singleton so we would only ever allow one global config, even when I create two instances of it with two different configs. 

Thank you.

**Comment by salvoravida** [comment]
you should be able to create 2 instance of it on 2 adalconfi1 and adalconfig2.js

export const authContext1 = new AuthenticationContext(adalConfig1);
export const adalApiFetch1 = (fetch, url, options) =>
  adalFetch(authContext1, adalConfig1.endpoints.api, fetch, url, options);


export const authContext2= new AuthenticationContext(adalConfig2);
export const adalApiFetch2 = (fetch, url, options) =>
  adalFetch(authContext2, adalConfig2.endpoints.api, fetch, url, options);


no?

**Comment by salvoravida** [comment]
i think that you cannot use 2 different ClientID from the same APP origin domain, but i need more investigation about it. i will let you know

**Comment by luminescent** [comment]
Yes, this is what I have tried, however, when creating the 2nd one, you'll
see that internally it uses the `adalConfig1`. So basically you cannot have
a different instance with a different config.

**Comment by salvoravida** [comment]
hum i thin that adal.js official cannot use 2 clientID at same time.

You should have 1 tenant and clientID (appID) and multiple endpoint api(servers)

so you have to get full Azure right on both endpoints apis with the same ClientID.

**Comment by luminescent** [comment]
Sadly that is outside of my control, and I need different clientIds and different endpoints. So I cannot use that configuration with one clientId and multiple endpoints that you suggested. 
I have looked through the code and I can see why it's not possible to have multiple clientIds, but thought I'd ask just in case.

**Comment by luminescent** [comment]
I presume we could close this as not possible, unless you have a different idea?

**Comment by luminescent** [comment]
Closing question as answer was given.
