### ISSUE TITLE
show a home page with login button

### ISSUE THREAD

**Issue by newtonsheikh** [salvoravida/react-adal#53]
i want my homepage/lading page to be some fancy page with login button, on click of this button i want to redirect to azure login page and upon successful login i want to go inside the main dash board. 

i am not able to achive it as the callback function is not propery documented. 

hwo to achieve this?

**Comment by twasono** [comment]
I think you can use `withAdalLoginApi HOC`

**Comment by salvoravida** [comment]
withAdalLoginApi HOC
change DO_NOT_LOGIN to true on index.js to stop login on index.js

```javascript
import MyPage from './myPageComponent';
import Loading from './Loading';
import ErrorPage from './ErrorPage';

const MyProtectedPage = withAdalLoginApi(MyPage, 
() => <Loading />, (error) => <ErrorPage error={error}/>);

<Route 
   path="/onlyLoggedUsers"
   render={ ()=> <MyProtectedPage /> } 
/>
```
