### ISSUE TITLE
How to set oauth state value?

### ISSUE THREAD

**Issue by nivuhebs** [salvoravida/react-adal#54]
In my application, i would have to pass few values in request and get the same value in response, which is usually done using state in Azure AD but when i use react-adal library, state value is not accepted as it is getting updated with GUID through code and it is not consider as configurable option.
So please let me the approach how would i be able to achieve this

**Comment by salvoravida** [comment]
can you share an example code?

**Comment by mbrevda** [comment]
Here is an example of how state would be expected to work: 
```js
export const adalConfig = {
  /* other opts */,
  state: {site: window.location.href}
}
```

**Comment by salvoravida** [comment]
i think you do not need state, becouse as you have an SPA after login you will be redirect on the same "index.js" entrypoint.

so you could save some value in localStorage, like currentPath and reload after to redirect on indexApp.js ...
