### ISSUE TITLE
How to handle "interaction_required" error when bootstrapping application with "runWithAdal"

### ISSUE THREAD

**Issue by mikkark** [salvoravida/react-adal#56]
I bootstrap my application using "runWithAdal" just like in the instructions. I get an "interaction_required" error after modifying the Service Principal in AAD to contain more permissions. I do not get the consent screen after logging in, instead I get redirected to the application, which does not work at all.

Should I catch this error somewhere and do something about it? In the general ADAL instructions in these cases one should trigger interactive login (like you would expect), but I don't even know how to do that with React ADAL because I don't see any hooks I could attach an error handler to while using runWithAdal.

**Comment by salvoravida** [comment]
can you show the error received in console?
