### ISSUE TITLE
adalFetch returns request and not response

### ISSUE THREAD

**Issue by jordynniara** [salvoravida/react-adal#57]
Is adalFetch just supposed to return a refreshed token that I then use to send a request or does it actually send the request. While trying to implement it I'm only receiving a promise of the request that is supposed to be sent, not the response. Looking at my network traffic it seems a call to my api is made but I'm getting a 204 response.
I'm using RxJs/ajax as my fetch object.
I've looked at other issues regarding adalFetch and I'm certain that  I'm implementing the call. It's after  I make the call that I need more clarity on.

**Comment by salvoravida** [comment]
```javascript
export function adalFetch(authContext, resourceGuiId, fetch, url, options) {
  return adalGetToken(authContext, resourceGuiId).then((token) => {
    const o = options || {};
    if (!o.headers) o.headers = {};
    o.headers.Authorization = `Bearer ${token}`;
    return fetch(url, o);
  });
}

```
is just a wrapper that set the token for you and return "your favorite fetch" ,,  window.fetch axios ....
