### ISSUE TITLE
Usage of adalApiFetch

### ISSUE THREAD

**Issue by hannehanen** [salvoravida/react-adal#6]
Hello. excuse me for beeing a bit of a beginner. But how do i use adalApiFetch to send my requests?
I for example use Axios to send http requests. An example would be lovely. Thanks.

// how to use the constant below..

export const adalApiFetch = (fetch, url, options) =>
  adalFetch(authContext, adalConfig.endpoints.api, fetch, url, options);
use adalApiFetch with your favorite "fetch" in your api call.

**Comment by salvoravida** [comment]
https://github.com/salvoravida/react-adal/issues/3
