### ISSUE TITLE
InvalidAuthenticationToken Access token validation failure.

### ISSUE THREAD

**Issue by AWR14** [salvoravida/react-adal#66]
I'm logging into my app fine, i'm then using react-adal to get the token

```
authentication.acquireToken(
        adalConfig.endpoints.api,
        (message, token, msg) => {
          if (token) {
            console.log("token", token);
            this.user(token);
          }
        }
      );
```

i'm then doing a call to the `https://graph.microsoft.com/v1.0/me` and getting the error `InvalidAuthenticationToken`, when i console .log the token its not empty

```
user async token => {
    try {
      const response = await axios.get(
        "https://graph.microsoft.com/v1.0/me",
        {
          headers: {
            Authorization: `Bearer ${token}`
          }
        }
      );

      console.log("response", response);
    } catch (error) {
      console.error(error);
    }
  };
```

Am i missing a step?

**Comment by M0W93** [comment]
So just to give you a quick example how to get the User Object from Graphs API with react-adal:

```
adalApiFetch(fetch, 'https://graph.microsoft.com/v1.0/me', {})
.then((response) => {
response.json()
    .then((responseJson) => {
        console.log(JSON.stringify(responseJson, null, 2));
    });
})
.catch((error) => {
console.error(error);
})
```

**Comment by AWR14** [comment]
Thanks @M0W93 

I've tried that and it didn't work

i have this in my config 

```
import { AuthenticationContext, adalFetch, withAdalLogin } from "react-adal";

export const adalConfig = {
  tenant: process.env.REACT_APP_TENANT,
  clientId: process.env.REACT_APP_CLIENTID,
  endpoints: {
    api: process.env.REACT_APP_CLIENTID
  },
  postLogoutRedirectUri: window.location.origin,
  redirectUri: `${process.env.REACT_APP_LOGIN_URL}/auth/openid/return`,
  cacheLocation: "localStorage"
};

export const authContext = new AuthenticationContext(adalConfig);

export const adalApiFetch = (fetch, url, options) =>
  adalFetch(authContext, adalConfig.endpoints.api, fetch, url, options);

export const withAdalLoginApi = withAdalLogin(
  authContext,
  adalConfig.endpoints.api
);


```

Everything works to login and can access the logged in user, just can't do a call to the graph api.

So using that code you pasted, gives me this error.

```
{
  "error": {
    "code": "InvalidAuthenticationToken",
    "message": "Access token validation failure.",
    "innerError": {
      "request-id": "b8ce1d02-f4e7-4437-9e4a-fbd70416dc24",
      "date": "2019-05-10T16:48:45"
    }
  }
}
```

Any ideas what i'm doing wrong?

**Comment by M0W93** [comment]
Does it say Invalid Auth Toke altough you use the adalApiFetch method?
Maybe not enough permissions?

**Comment by AWR14** [comment]
@M0W93 yeah even using adalApiFetch

permissions i have are `Sign in and read user profile`, which has been working for ages. Then we wanted to add a feature that required user being in a certain group so have `Read all groups` enabled.
These are both delegated permissions on the App.

Is any other permission required?

**Comment by AWR14** [comment]
@M0W93 i'm getting the following error using

```
adalApiFetch(fetch, "https://graph.microsoft.com/v1.0/me", {})
        .then(response => {
          response.json().then(responseJson => {
            console.log(JSON.stringify(responseJson, null, 2));
          });
        })
        .catch(error => {
          console.error(error);
        });

```
`{
  "error": {
    "code": "InvalidAuthenticationToken",
    "message": "Access token validation failure.",
    "innerError": {
      "request-id": "7a455d55-0b07-4310-ab39-7540115f71e2",
      "date": "2019-05-13T08:48:56"
    }
  }
}`

**Comment by AWR14** [comment]
@M0W93 When the user signs in i'm redirecting to `http://localhost:3000/auth/openid/return` if that helps

**Comment by noobling** [comment]
Same issue here I get an access token but interestingly it doesn't authenticate with the graph microsoft endpoint. Could be something to do with `portal.azure` configuration, however the token I get from `msal js` is working ...

**Comment by aman5898** [comment]
Same here , getting the error
{
  "error": {
    "code": "InvalidAuthenticationToken",
    "message": "Access token validation failure. Invalid audience.",
    "innerError": {
      "request-id": "c0ad0d2a-b645-4c0d-800d-2d700c136f25",
      "date": "2019-06-24T06:06:46"
    }
  }
}

**Comment by frankhale** [comment]
> InvalidAuthenticationToken

I've got the same issue as stated above by multiple users. I've noticed that minimal ADAL sample here: https://gist.github.com/psignoret/50e88652ae5cb6cc157c09857e3ba87f returns an authentication token that is more than 300 bytes larger and works for fetching data from graph.microsoft.com. 

react-adal's authentication token is around 1330 bytes for me and the minimal ADAL example returns one 1600 bytes. The token in the minimal example works, the one in react-adal does not. 

Why is there a discrepancy in the token returned and how can we resolve this?

Logging in works and it appears as though everything went fine but something is clearly not correct.

**Comment by frankhale** [comment]
I think I see where the misunderstanding is and I didn't see it until now. The auth token that is returned from logging in is not the same token you use to access graph.microsoft.com. Looks like you have to acquire another token to access graph.microsoft.com. Have a look on line 70 of this minimal ADAL example: https://gist.github.com/psignoret/50e88652ae5cb6cc157c09857e3ba87f

**Comment by salvoravida** [comment]
export const adalFetchGraph = (fetch, url, options) =>
  adalFetch(authContext, 'https://graph.microsoft.com', fetch, url, options);
