### ISSUE TITLE
Not working with file system  uri 

### ISSUE THREAD

**Issue by shivshankar3578** [salvoravida/react-adal#70]
As electron serve files via file:// protocol after building the app while Microsoft AAD auth does not allow file system uri so I'm getting error 

> AADSTS500111: The reply uri specified in the request has an invalid scheme.

because of invalid **redirectUri** (for me It's default window.location.href)
Need quick fix
Thanks in advance

**Comment by mbrevda** [comment]
you'll need to register that url in the azure portal. Looking for a better solution mysef!

**Comment by salvoravida** [comment]
@shivshankar3578 yes in azure AAD you have to register the correct return url as 
@mbrevda
