### ISSUE TITLE
Getting error after logged in

### ISSUE THREAD

**Issue by aman5898** [salvoravida/react-adal#73]
I am using react-adal, in it at my index page there is a login button after clicking on it user gets redirected to login and after successful login he should reach back to route '/user' but instead after successful login on reaching to '/user' the application shows nothing and a message is displayed in the log which is
message: "AADSTS500011: The resource principal named values was not found in the tenant named 72f988bf-86f1-41af-91ab-2d7cd011db47. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You might have sent your authentication request to the wrong tenant.
↵Trace ID: 7699917a-43e6-4a74-aee3-996966f03e00
↵Correlation ID: c8d895bd-3ba5-41ba-9038-140d93f73170
↵Timestamp: 2019-06-18 05:28:39Z"
msg: "invalid_resource"
I have shared all the files here https://stackoverflow.com/questions/56628128/getting-an-error-while-using-react-adal-in-login

**Comment by salvoravida** [comment]
endpoints: {
    api: 'values',
  },

the endpoints.api must be an Azure ResourceId and the clientId (your app) must be authorized to that resource.

**Comment by aman5898** [comment]
I am not calling any API right now from this app

**Comment by salvoravida** [comment]
react-adal is just a wrapper of official adal.js azure library.
so for Azure authorization  you have to look to azure guide or adal.js docs

https://github.com/AzureAD/azure-activedirectory-library-for-js

**Comment by aman5898** [comment]
Yaa, got it thanx!
