### ISSUE TITLE
Allow alternate redirect url

### ISSUE THREAD

**Issue by mbrevda** [salvoravida/react-adal#74]
As a superset of #54, it would be useful to allow setting a dynamic redirect url, which may differ from the redirectUrl option.

Currently AAD is quite strict regarding redirect urls, allowing only the domains that exactly match what listed in the azure portal. This can sometimes cumbersome when the domain is dynamic, as for example with Netlify [deploy previews](https://www.netlify.com/blog/2016/07/20/introducing-deploy-previews-in-netlify/), where every branch/pr is assigned a unique url.

To work around this and still adhere to the security principles of the redirect uri, a redirect proxy can be setup on a whitelisted redirect url which could parse the incoming hash and determine the correct url to call (presumably matching the domain against it's own whitelist in order to weaken security).

To implement such a solution, react-adal would have to supplement state with a user-supplied redirect url and perhaps offer a helper function which can be installed on the "proxy" page. The proxy would then redirect to the original requesting page whenever it's called.

<details>
<summary>By way of illustration, this is what the proxy page might look like</summary>

```html
<!DOCTYPE html>
<html>
    <head></head>
    <body>
        <script>
        // get  hash
        var hash = decodeURIComponent(window.location.hash)

        // convert to object of key: value
        var data = Object.fromEntries(hash.split('&').map(item => item.split('=')))

        // get redirectUrl if set
        const {redirectUrl, ...state} = JSON.parse(data.state)

        var dest = new URL(redirectUrl + hash)

        if (redirectUrl && redirectUrl !== window.location.href) {
            window.location.replace(dest)
        }
        </script>
    </body>
</html>
```
</details>

**Comment by salvoravida** [comment]
that's not a problem of react-adal
