### ISSUE TITLE
How would you deal with configuration changes depending on user input (e.g. prompt method)?

### ISSUE THREAD

**Issue by isopterix** [salvoravida/react-adal#75]
I have the following ADAL config:

```js
export const adalConfig = {
  tenant: "xxx.onmicrosoft.com",
  clientId: "xxx",
  endpoints: {
    api:
      "xxx"
  },
  cacheLocation: "localStorage",
  extraQueryParameter: "prompt=login"
};
```

Now I would like to change the **extraQueryParameter** based on user input... e.g. to switch from "prompt=login" to "prompt=none" to control if SSO is used or not...

How can I achieve that?

As the config is initialized already before react is initialized, how can I change that configuration afterwards?

**Comment by salvoravida** [comment]
can you explain better your use case?

if it is the case, you have some public /route on your app, so your private app is under withAdalLogin(...)

on the public app, you have to change dinamically adalConfig, and re create the authContext...
