### ISSUE TITLE
cancel request

### ISSUE THREAD

**Issue by rpk-red** [salvoravida/react-adal#78]
Is it possible to cancel adal request using actionController.abort()? And in what way can it be done?

**Comment by salvoravida** [comment]
what do you mean for adal request?
adalFetch?
it depends on your "fetch" , like window.fetch or axios or what you want.

feel free to reopen if it is not clear.

**Comment by jorgen-kaxig** [comment]
I need to do this. I use axios. I know about the "cancel token" as described in this [Medium article](https://medium.datadriveninvestor.com/aborting-cancelling-requests-with-fetch-or-axios-db2e93825a36).
But how to implement this with react-adal is not clear.
I need this to avoid the react error "Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function."
