### ISSUE TITLE
Application loads twice on First Auth with Razzle SSR 

### ISSUE THREAD

**Issue by vbutani** [salvoravida/react-adal#79]
Thanks for the amazing library!

I am facing some issue while using it with Razzle SSR app.

I tried to put all the logic of client.js within runWithAdal() success callback, it didn't work as I think it needs to hydrate the component mentioned in client.js first.

Then I added runWithAdal() in Home component. it works fine, but the Application gets mounted/loaded twice on authentication. could you please advise how to solve this issue.

I used react-adal for other client react apps and it works fine without issue, but in case of SSR this issue occurs. I am adding my code snippets as below.

**client.js**
```

import App from './App';
import BrowserRouter from 'react-router-dom/BrowserRouter';
import React from 'react';
import { hydrate } from 'react-dom';

hydrate(
  <BrowserRouter>
    <App />
  </BrowserRouter>,
  document.getElementById('root')
);

if (module.hot) {
  module.hot.accept();
}

```

**App.js**
```

import React from 'react';
import Route from 'react-router-dom/Route';
import Switch from 'react-router-dom/Switch';
import Home from './Home';
import './App.css';

const App = () => (
  <Switch>
    <Route exact path="/" component={Home} />
  </Switch>
);

export default App;

```

**Home.js**

```

import React from 'react';
import logo from './react.svg';
import './Home.css';
import { runWithAdal, AuthenticationContext } from 'react-adal';

 const adalConfig = {
  tenant: 'b9ef5201-33b0-4725-bbb8-7900d11a6c74',
  clientId: '52f86c14-6980-4e35-bd10-141a3e5e8836',
  redirectUri: 'http://localhost:3000/',
  cacheLocation: 'localStorage'
};

const authContext = new AuthenticationContext(adalConfig);

runWithAdal(authContext, () => Home);

class Home extends React.Component {

  componentDidMount() {
    console.log('Home Mounted');
  }

  render() {
    return (
      <div className="Home">
          Welcome to Razzle
      </div>
    );
  }
}

export default Home;
```

**Comment by salvoravida** [comment]
look at readme example:

runwithAdal should start before any react app, otherwise you will have double app rendered even into iframe

import { runWithAdal } from 'react-adal';
import { authContext } from './adalConfig';

const DO_NOT_LOGIN = false;

runWithAdal(authContext, () => {

  // eslint-disable-next-line
  require('./indexApp.js');

},DO_NOT_LOGIN);

**Comment by vbutani** [comment]
> look at readme example:
> 
> runwithAdal should start before any react app, otherwise you will have double app rendered even into iframe
> 
> import { runWithAdal } from 'react-adal';
> import { authContext } from './adalConfig';
> 
> const DO_NOT_LOGIN = false;
> 
> runWithAdal(authContext, () => {
> 
> // eslint-disable-next-line
> 
> 
> },DO_NOT_LOGIN);

```
import { runWithAdal } from 'react-adal';
import { authContext } from './adalConfig';
import App from './App';
import BrowserRouter from 'react-router-dom/BrowserRouter';
import React from 'react';
import { hydrate } from 'react-dom';

const DO_NOT_LOGIN = false;

runWithAdal(authContext, () => {

// eslint-disable-next-line
hydrate(
  <BrowserRouter>
    <App />
  </BrowserRouter>,
  document.getElementById('root')
);


},DO_NOT_LOGIN);

if (module.hot) {
  module.hot.accept();
}


```


Sorry for the delayed response. I followed it by putting hydrate method call of Client.js file in success callback of runWithAdal(), but I guess due to SSR hydrating it is not loading app properly.(Client.js is the starting page for SSR based client application)

I observed that if I put logic of runWithAdal() using adal.js methods in index.html and load the client.js file on authentication than it works fine.

Could you please advise how I can achieve it using runWithAdal in Client.js, just want to make sure if I am not missing anything important while using runWithAdal in Client.js file. Many Thanks.

**Comment by salvoravida** [comment]
in your case you should do

index.js 
```

import { runWithAdal } from 'react-adal';
import { authContext } from './adalConfig';

const DO_NOT_LOGIN = false;

runWithAdal(authContext, () => {

require('./client.js');

},DO_NOT_LOGIN);
```
