### ISSUE TITLE
Change README To Use Create React App

### ISSUE THREAD

**Issue by opticyclic** [salvoravida/react-adal#81]
The instructions in the README would be easier to follow if you based them on `create-react-app` and removed any unnecessary extras.

Right now you confuse the situation by adding `react-redux` and `store` as they don't seem to be necessary.

It would be clearer if you just showed how to do it from `create-react-app` as that is the easiest way to get started with a new react project.

e.g. 

* npx create-react-app my-app
* cd my-app
* npm install react-adal
* copy index.js to indexApp.js
* change index.js to the code in the README
* add adalConfig from the README
* update tenant/client fro m azure
* npm start

The "copy index.js to indexApp.js" is the key bit that isn't clear because you have added `react-redux` and `store`  in your example and it took a while to realise what was being done.

**Comment by salvoravida** [comment]
yes you are right, i will rewrite readme asap.

thanks!
