### ISSUE TITLE
Token refresh with adalGetToken

### ISSUE THREAD

**Issue by zsid** [salvoravida/react-adal#82]
Hi,

I have a problem with token refresh. I am trying to use `adalGetToken` to get the `token` because `adalGetToken` should renew the token if it has expired.

Looking at the interface:
```
/**
 * Return user token
 * @param authContext Authentication context
 * @param resource Resource GUID ot URI identifying the target resource.
 */
export function adalGetToken(
    authContext: AuthenticationContext,
    resourceUrl: string
): Promise<string | null>;
```
I am struggling to pass the valid `resourceUrl`. Looking at the source code there is a function `AuthenticationContext.prototype._getNavigateUrl` that you call to create the `url` but it is not exposed in the `context`.

Can you provide an example of what the `resourceUrl` should be?

**Comment by salvoravida** [comment]
is the guiId of your Azure api endpoint app
