### ISSUE TITLE
Using withAdalLogin example, after login still redirect to the home page

### ISSUE THREAD

**Issue by TianyuHou** [salvoravida/react-adal#83]
After trying the withAdalLogin example, I found it always redirect to the home page after the user successfully login, not redirect to the specific route in the <Rotue path="/onlyLoggedUsers">. I figured out it may because of the AAD can only redirect to base URL. I just wonder do we have any solutions to do so? like how to check if the user has login into AAD?

**Comment by BlackFenix2** [comment]
on your AdalConfig object you have to specify a postLogoutRedirectUri propeprty in order to redirect the user to their previous route.

i have a snippet below on how this is done, i included a window check for SSR


```js
// redirect login url to client's return URL
  postLogoutRedirectUri:
    typeof window !== 'undefined' &&
    window &&
    window.location.href.split('?')[0].split('#')[0],
```

**Comment by salvoravida** [comment]
yes you have to set postLogoutRedirectUri in the config object
