### ISSUE TITLE
how to set response redirect uri 

### ISSUE THREAD

**Issue by saostad** [salvoravida/react-adal#89]
Hi, 
with the default configuration, it uses current uri in the browser as response uri but if that page is different from what is in azure registration config it fails to login.
how to set response redirect uri?

**Comment by salvoravida** [comment]
adalConfig = {
    tenant: '..............7',
    clientId: '1.....................93e62',
    endpoints: {
        api: '140.......................e62',
    },
    postLogoutRedirectUri: window.location.origin,  <---- put your redirect uri
    cacheLocation: "localStorage",
};
