### ISSUE TITLE
Graph Call is not happening with the generated idToken

### ISSUE THREAD

**Issue by KoushikGoramane** [salvoravida/react-adal#91]
If I call the microsoft graph with the generated token it is showing error. How to call the graph api and get the logged in user details.

Error
{
  "error": {
    "code": "InvalidAuthenticationToken",
    "message": "Access token validation failure. Invalid audience.",
    "innerError": {
      "request-id": "df2ddcfa-a2d0-42e8-80b2-b8323888191d",
      "date": "2019-10-14T11:51:06"
    }
  }
}

**Comment by mudasar** [comment]
you have to get an auth token using the Api Fetch method and than use that token to make a graph api call it'll work.
(in the auth token request you need to ask for scopes )
